# 1. Specify the version for docker-compose.yml
version: "3.8"

# 2. Generate the serivces needed (redis)
services:
  redis:
    container_name: "redis"
    image: redis:alpine
    # Specify the redis.conf file to use and add a password.
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    ports: 
      - "6379:6379"
    # map the volumes to that redis has the custom conf file from this project.
    volumes: 
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  go:
    container_name: "redisapi"
    build:
      # build the image using the Dockerfile we have in this project. Can use an image instead.
      context: .
    ports:
      - "8080:8080"